title: Svadba Vladko & Lenka
description: Informácie k našej svadbe.
show_downloads: false
google_analytics:
theme: jekyll-theme-merlot
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"